### ISSUE TITLE
MongoDB Data Layer

### ISSUE THREAD

**Issue by Esteban-De-la-Sexface** [miLibris/flask-rest-jsonapi#10]
MongoDB data layer is documented but not supported in the current version. Are there any plans to release the MongoDataLayer?

**Comment by akira-dev** [comment]
First the documentation is not update to date but i will release a new one in few days. There is only the documentation of release 0.5.X available yet. In the last version of Flask-REST-JSONAPI i dropped the default mongo_data_layer because it was not enough agnostic and the filtering system was very poor. So I decided to move it from the Flask-REST-JSONAPI to my own project. But if you want I can send to you my own mongo_data_layer to save your time just give me your email address.

**Comment by Esteban-De-la-Sexface** [comment]
My email address is steven@vearsa.com, that would be great. Thanks

**Comment by akira-dev** [comment]
It is sent

**Comment by Arkoprabho** [comment]
@akira-dev Can you email the data layer to me as well? How do we integrate flask-rest-jsonapi with mongoengine?

**Comment by vivekkumar2696** [comment]
@akira-dev It would be great if you could email the mongo data layer to me as well. Or do you have it documented somewhere?
