### ISSUE TITLE
Support conforming filter syntax

### ISSUE THREAD

**Issue by matthewdias** [miLibris/flask-rest-jsonapi#30]
The way `flask-rest-jsonapi` accepts filter params doesn't match the `JSONAPI` spec, and therefore makes it really ugly to filter with `JSONAPI` clients that support it. For example in Ember I have to do:

```
filter: `[${JSON.stringify({
  name: 'name',
  op: 'eq',
  val: name
})}]`
```

as opposed to what I can normally do with conforming server implementations:

```
filter: { name }
```
You can see why this might not be ideal.

**Comment by akira-dev** [comment]
The only thing mensioned in JSONAPI specification (http://jsonapi.org/format/#fetching-filtering) is :

> Note: JSON API is agnostic about the strategies supported by a server. The
`filter` query parameter can be used as the basis for any number of filtering
strategies.

What you take about Filtering (http://jsonapi.org/recommendations/#filtering) is just a recommandation, it does not belong to the specification so ```flask-rest-jsonapi``` is really compliant with JSONAPI specification.

I don't use the recommandation of Filtering because it is a very poor strategie for filtering. Instead of that if you want to get the filtering stratagie mensioned in JSONAPI recommandation you can create your own data layer inherited from the default SQLAlchemy data layer and rewrite the filter_query method to do what you want.

**Comment by matthewdias** [comment]
gotcha.
