### ISSUE TITLE
Unable to add blueprints without errors

### ISSUE THREAD

**Issue by zengoma** [miLibris/flask-rest-jsonapi#35]
I don't know if this is an issue or just my ignorance but I am having difficulty adding my api routes with a blue print prefix:

app/api/views:
```
from app.api.resources import UserList, UserDetail, MaterialList, MaterialDetail
from flask import Blueprint
from flask_rest_jsonapi import Api

json_api = Blueprint('api', __name__, url_prefix='/api')  # @todo figure out how to add blueprints
api = Api(blueprint=json_api)

# User routes
api.route(UserList, 'user_list', '/users')
api.route(UserDetail, 'user_detail', '/users/<string:id>')

# Material routes
api.route(MaterialList, 'material_list', '/materials')
api.route(MaterialDetail, 'material_detail', '/materials/<string:id>')
```
app/__init__.py

```
# -*- coding: utf-8 -*-
from flask import Flask
from app.api.views import api
from app.database import db
from app.cors import cors
from app.auth.views import auth


def create_app():
    app = Flask(__name__)
    app.config.from_object('config')
    db.init_app(app)
    cors.init_app(app)
    api.init_app(app)
    app.register_blueprint(auth)
    return app


def setup_database(app):
    with app.app_context():
        db.create_all()


app = create_app()
setup_database(app)
```

Now if I visit http://localhost:5000/api/materials I receive the following error:

werkzeug.routing.BuildError: Could not build url for endpoint 'material_list'. Did you mean 'api.material_list' instead?

The obvious solution that springs to mind would be to change the endpoint name in routes and schemas to: api.material_list

however the error is now:

werkzeug.routing.BuildError: Could not build url for endpoint 'api.material_list'. Did you mean 'api.api.material_list' instead?

If I remove the blueprint:

`api = Api()`

and visit: http://localhost:5000/materials everything works perfectly!

I've tried defining the blueprint in every way conceivable but I'm still getting the same error. If this is not an issue and I'm just being a noob please forgive me.

**Comment by zengoma** [comment]
PS: If you need to see my schema and resource setup I can include that too.

**Comment by traut** [comment]
try passing your blueprint like an app, like that: `api = Api(json_api)`

**Comment by traut** [comment]
+ it seems you're missing[ blueprint registration](http://flask.pocoo.org/docs/0.12/blueprints/#registering-blueprints)?

**Comment by zengoma** [comment]
Thanks for the advice traut, I appreciate it. I have already tried registering the blueprint in --init--.py like this:
`app.register_blueprint(json_api)`
but it throws the exact same error. I've also tried the following in the view file:
`api = Api(json_api)`

and this as well

```
api = Api()
api.blueprint = json_api
```

I even tried this in --init--.py

`api.init(app, json_api)`

All these methods including the one in my original example are simply trying to achieve the same purpose of registering the blueprint in a different way. This must be true, because if I remove them, then the /api url prefix throws a 404 not found error when I visit it in the browser or with postman. The fact that I'm getting a 500 error instead of a 404 must surely mean that the /api blueprint has registered correctly on the url path. I have also printed the endpoint on my console when I visit the url and it prints "api.material_list" which furhter proves that the api blueprint is registering? Am I correct in assuming that? Unless I've completely missed something here there is something else going on? Any ideas?

**Comment by traut** [comment]
@zengoma please share your `MaterialList` class definition

**Comment by zengoma** [comment]
sure, here it is (a quick note since my original posts. I've refactored my code to replace the string uuid id on all tables to the regular integer auto-increment setup, this of course does not change anything regarding the blueprint issue)

resources.py
```
. . .

# Create material resource list
class MaterialList(ResourceList):

    def before_create_object(self, data, view_kwargs):
        if data["description"] is not None:
            data['description'] = Markup(data['description'])

    schema = MaterialSchema
    data_layer = {'session': db.session,
                  'model': Material,
                  'methods': {
                      'before_create_object': before_create_object
                  }}
. . .
```
Please let me know if there are any other snippets you would like to see.

**Comment by traut** [comment]
could you please prepare a test case/code, stitching together snippets of your code? This would be very helpful.  have a very similar code and it works. Having a test case would help

**Comment by zengoma** [comment]
unfortunately I have just come from a php background and only just learned python in the last couple weeks. I haven't tackled test driven development yet, and have just been hacking... but I will get there. I've prepared a [skeleton app](https://github.com/zengoma/flask-rest-jsonapi-skeleton-app) based on the "First example" with the Person and Computer Schema. I copied and pasted the code so it is an exact replica. It also throws the error when I visit http://localhost:5000/api/persons, but http://localhost:5000/api/computers is strangely enough working fine (with no rows in the table). Clone the repository and run setup. You'll be able to see the full error stack and a man of your calibre should solve it in 5 minutes. It is probably a novice error, and for that I am sorry for raising an issue.

**Comment by akira-dev** [comment]
I have seen in your skeleton app that your schemas are not setup correctly. If you want to use a blueprint like that ```Blueprint('api', __name__, url_prefix='/api')``` you must add the api prefix to all your endpoints in your schemas. So ```self_view = 'person_detail'``` becomes ```self_view = 'api.person_detail'```. First update your schemas and tell me if it fix the issue. Not that I'm talking about about the api prefix, the first parameter of your blueprint not the url prefix. For example: ```Blueprint('api_prefix', __name__, url_prefix='/api')``` your schema must looks like this ```self_view = 'api_prefix.person_detail'```.

**Comment by zengoma** [comment]
@akira-dev  , thank you, you are a genius - that has solved the problem entirely! When I originally tried this I added the api prefix to the route declaration as well. As you have correctly pointed out the prefixes should only be used in the schemas and not in the routes. I thank both you and @traut for efforts, i owe you each a beer... bottoms up!

**Comment by anuragagarwal561994** [comment]
This is a very common use case, I figured it out from the issue above. An example would be good in the docs.

**Comment by gsverma** [comment]
@zengoma Hi, can I see your resource set up. I'm doing something very stupid I guess; its working without blueprints, but not with blueprints. My project setup is something like what they recommend in flask-restful.

**Comment by anuragagarwal561994** [comment]
Just share the exception that is being thrown, may be I will be able you help you better.
```python
from flask import Blueprint
from flask_json_api import Api

api = Api(blueprint=Blueprint('api', __name__, url_prefix='/api'))
```

Now when you are declaring schemas everywhere for view_name, prefix with ``api.``.

```python
class ExampleSchema(Schema):
    class Meta:
         type_ = 'example'
         self_view = 'api.example_detail'
```

Similarly in relationships too, but not while declaring routes.

```python
api.route(ExampleDetail, 'example_detail', '/example/<int:id>')
```

Then I guess there would be no problem. If you are still seeing 404s then try by not passing the app while declaring the api extension and instead after declaring all the routes, do init_app.

```python
# Instead of
api = Api(app, blueprint=Blueprint('api', __name__, url_prefix='/api'))
api.route(ExampleDetail, 'example_detail', '/example/<int:id>')
# Use this
api = Api(blueprint=Blueprint('api', __name__, url_prefix='/api'))
api.route(ExampleDetail, 'example_detail', '/example/<int:id>')
api.init_app(app)
```
I don't know why this happens, but after doing some hit and trials after a full revamp of my code, I discovered this was the problem for which I spent quite some time before I figured it out by myself.

If you need any guidance for project structure, this is what I am following at present after several rounds of rework:
```
project/
    __init__.py
    models
        __init__.py   -> import all the models under this package and make them available on top
        group1.py   -> group of models, which might have same base model will help in code reduction
        group2.py
        group3.py
    schemas
        __init__.py   -> import all the schemas under this package and make them available on top
        group1.py   -> group of schemas, which might have same base schema
        group2.py
        group3.py
    resources
        __init__.py   -> import all the resources
        group1.py   -> use the models, schemas to declare resources and routes
        group2.py
        group3.py
```

If you don't have groups you can also declare models and schemas as modules instead of packages. This structure reduces cyclic dependencies all together (the thing that bugged me a lot), since model declarations doesn't require other models or schemas or resources. Same goes with schema declaration. But resources that need both, can use them independently and no one resource depends on other resource, no issues of cyclic dependency at all.

What I further suggest is to make a helper class Endpoint as utils. Declaring routes like ``api.route`` will become a lot tiring process and it will anyways look ugly at end. Try to make your routes look like a dictionary or mapping of views to resource and routes (better readability). Then finally import all such endpoint mappings and declare your routes together under a loop.

**Comment by gsverma** [comment]
Thanks a ton @anuragagarwal561994 !! init_app() was all it needed. After your comment only I had a close look at init.py above. Other wise I had literally messed up my schemas n resources.

**Comment by anuragagarwal561994** [comment]
The whole documentation is based on one example, which is good but it doesn't cover a lot of other use cases or recipes (like code structure etc.) that could really improve the documentation. Personally I find Flask-Rest-JSONAPI awesome.

I switched from Flask-RESTless, although I had to now write a ton of lines extra but the structure then becomes quite flexible and scalable for future purposes. This library gives me a lot of speed advantage over Flask-Restless, also in recent times there has been no development on Flask-Restless. But a little on documentation side can be improved. There are lot of hidden methods under Modules API section, which I somewhat reimplemented because I didn't know they were already there.

Ps. If you are having speed issues, try changing the lazy attribute of your relationships. Even though the default value should yield the results only when used. Every time you query your models via API, all the related models are queried, I  checked it via SQLALCHEMY_ECHO option. I still don't know how to resolve this, right now I am using `lazy='noload'`, only needing `lazy='select'` when I am actually querying over it.

**Comment by gsverma** [comment]
@anuragagarwal561994  Yeah tons of code compared to Restless (Even We are migrating from Restless; technically we haven't finalized any alternatives but are now reviewing flask-rest-jsonapi). Its lot better compared to Flask-Restful (Our first alternative - though earlier we had switched from restful to restless) which involved lot more manual setup. 
And thanks on the heads-up on relationships; today I was going to work on that exact thing.

**Comment by gsverma** [comment]
@anuragagarwal561994 Is there any chance you have used OAuthlib in your API? I am getting a 401 for resource access, I tried following RFCs on how to request resources using Bearer token. I have done till the point where I get bearer token (I am using implicit grant); I am stuck at using this token for accessing oauth protected resources. Probably I have missed out something while mapping oAuth decorators/methods while implementing it with flask-rest-jsonapi, though things look so straight forward.

**Comment by anuragagarwal561994** [comment]
I am really sorry @gsverma, I haven't yet touched the authentication part. I will ping you once I am through with it.

**Comment by gsverma** [comment]
Figured that out! RFC 6750. requests to oAuth protected endpoints need to have an additional header in the form of:  <<"Authorization" = "Bearer '<bearer_token_here>' >>.
