### ISSUE TITLE
include multiple related resources

### ISSUE THREAD

**Issue by tzimme** [miLibris/flask-rest-jsonapi#56]
this issues is probably similar to [#29](https://github.com/miLibris/flask-rest-jsonapi/issues/29) only the suggested answer doesn't solve it.

in a request like this:
 api/author/123/?include=articles.comments,articles.ratings

only ratings are included(or only comments, depending on what comes last) never both.

**Comment by Natureshadow** [comment]
Looking at https://github.com/miLibris/flask-rest-jsonapi/blob/master/flask_rest_jsonapi/schema.py#L73 , it seems that only one of the includes can end up in the result, because the relation_field is overwritten in each iteration of the loop. The logic here seems entirely broken; having multiple includes in the URL can not work under any circumstances. I also doubt that it worked out for issue #29 in the end.

**Comment by Natureshadow** [comment]
I stand corrected. The attribute set in that line seems to be completely irrelevant, as neitehr Flask-REST-JSONAPI nor marshmallow nor marshmallow_jsonapi ever look at it.

**Comment by Natureshadow** [comment]
OK, it's not irrelevant. I am completely lost now regarding how that fits together…

**Comment by Natureshadow** [comment]
My confusion was lifted ;).
